// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGBGVU7TgkAVJexsxjxaEz52qTABEsE8',
    appId: '1:685774497005:web:d1d5307dda11bcedf898e4',
    messagingSenderId: '685774497005',
    projectId: 'ghodacare-844d6',
    authDomain: 'ghodacare-844d6.firebaseapp.com',
    storageBucket: 'ghodacare-844d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJqXt51TRSlnkAHIyhoM3fCz8Ikudv3HY',
    appId: '1:685774497005:android:7366dfc1ffda8b06f898e4',
    messagingSenderId: '685774497005',
    projectId: 'ghodacare-844d6',
    storageBucket: 'ghodacare-844d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVX1khR2FlrPd4ZmqRS_X1t3aAYcqm-4g',
    appId: '1:685774497005:ios:040ca60fe5fb93b6f898e4',
    messagingSenderId: '685774497005',
    projectId: 'ghodacare-844d6',
    storageBucket: 'ghodacare-844d6.firebasestorage.app',
    iosBundleId: 'com.example.ghodacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVX1khR2FlrPd4ZmqRS_X1t3aAYcqm-4g',
    appId: '1:685774497005:ios:040ca60fe5fb93b6f898e4',
    messagingSenderId: '685774497005',
    projectId: 'ghodacare-844d6',
    storageBucket: 'ghodacare-844d6.firebasestorage.app',
    iosBundleId: 'com.example.ghodacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMGBGVU7TgkAVJexsxjxaEz52qTABEsE8',
    appId: '1:685774497005:web:504ce820a8a4e8aaf898e4',
    messagingSenderId: '685774497005',
    projectId: 'ghodacare-844d6',
    authDomain: 'ghodacare-844d6.firebaseapp.com',
    storageBucket: 'ghodacare-844d6.firebasestorage.app',
  );
}
